---
DiscordBotsOrg:
  enabled: false # Whether to post server count to http://discordbots.org or not.
  token: token # This is the token you got from http://discordbots.org.
  refreshRate: 1800000 # Refresh rate in miliseconds.
BotsDiscordPw:
  enabled: false # Whether to post server count to http://bots.discord.pw or not.
  token: token # This is the token you got from http://bots.discord.pw.
  refreshRate: 1800000 # Refresh rate in miliseconds.
